// Generated by BUCKLESCRIPT VERSION 1.7.1, PLEASE EDIT WITH CARE
'use strict';

var Page       = require("./page.js");
var Curry      = require("bs-platform/lib/js/curry.js");
var ReactDOMRe = require("reason-react/lib/js/src/reactDOMRe.js");

ReactDOMRe.renderToElementWithId(Curry._4(Page.createElement, /* [] */0, /* None */0, /* None */0, /* () */0), "container");

/*  Not a pure module */
