// Generated by BUCKLESCRIPT VERSION 1.7.1, PLEASE EDIT WITH CARE
'use strict';

var Curry    = require("bs-platform/lib/js/curry.js");
var React    = require("react");
var $$String = require("bs-platform/lib/js/string.js");
var ReactRe  = require("reason-react/lib/js/src/reactRe.js");

var componentDidMount = ReactRe.Component[0];

var componentWillUpdate = ReactRe.Component[1];

var componentDidUpdate = ReactRe.Component[2];

var componentWillReceiveProps = ReactRe.Component[3];

var componentWillUnmount = ReactRe.Component[4];

var getInstanceVars = ReactRe.Component[5];

var jsPropsToReasonProps = ReactRe.Component[6];

var getInitialState = ReactRe.Component[7];

var name = "Page";

var callbackUrl = encodeURIComponent("http://localhost:54380/");

var requiredPermissions = encodeURIComponent($$String.concat(" ", /* :: */[
          "playlist-read-private",
          /* :: */[
            "playlist-read-collaborative",
            /* [] */0
          ]
        ]));

var spotifyUrl = "https://accounts.spotify.com/authorize/?client_id=35988437b3404ab08d67eaced43c4997&response_type=code&redirect_uri=" + (callbackUrl + ("&scope=" + (requiredPermissions + "&state=34fFs29kd09")));

function render() {
  return React.createElement("div", undefined, React.createElement("h1", undefined, "Step 1: Log into Spotify"), React.createElement("p", undefined, React.createElement("a", {
                      href: spotifyUrl
                    }, "Log In")));
}

var Page_008 = /* Stateful */ReactRe.Component[8];

var Page_009 = /* JsProps */ReactRe.Component[9];

var Page_010 = /* InstanceVars */ReactRe.Component[10];

var Page = /* module */[
  /* componentDidMount */componentDidMount,
  /* componentWillUpdate */componentWillUpdate,
  /* componentDidUpdate */componentDidUpdate,
  /* componentWillReceiveProps */componentWillReceiveProps,
  /* componentWillUnmount */componentWillUnmount,
  /* getInstanceVars */getInstanceVars,
  /* jsPropsToReasonProps */jsPropsToReasonProps,
  /* getInitialState */getInitialState,
  Page_008,
  Page_009,
  Page_010,
  /* name */name,
  /* spotifyUrl */spotifyUrl,
  /* render */render
];

var include = ReactRe.CreateComponent([
      name,
      getInstanceVars,
      getInitialState,
      componentDidMount,
      componentWillReceiveProps,
      componentWillUpdate,
      componentDidUpdate,
      componentWillUnmount,
      jsPropsToReasonProps,
      render
    ]);

var wrapProps = include[1];

var createElement = Curry._1(wrapProps, /* () */0);

var comp = include[0];

exports.Page          = Page;
exports.comp          = comp;
exports.wrapProps     = wrapProps;
exports.createElement = createElement;
/* callbackUrl Not a pure module */
