// Generated by BUCKLESCRIPT VERSION 1.6.0, PLEASE EDIT WITH CARE
'use strict';

var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions");

var NewListener = Caml_exceptions.create("Electron.EventEmitter.Event.NewListener");

var RemoveListener = Caml_exceptions.create("Electron.EventEmitter.Event.RemoveListener");

var Event = /* module */[
  /* NewListener */NewListener,
  /* RemoveListener */RemoveListener
];

var Elim = /* module */[];

var Listener = /* module */[/* Elim */Elim];

var EventEmitter = /* module */[
  /* Event */Event,
  /* Listener */Listener
];

var BrowserWindow = /* module */[];

var Certificate = /* module */[];

var CommandLine = /* module */[];

var Event$1 = /* module */[];

var ImportCertificateOptions = /* module */[];

var LoginAuthInfo = /* module */[];

var LoginItemSettings = /* module */[];

var LoginRequest = /* module */[];

var Menu = /* module */[];

var NativeImage = /* module */[];

var Task = /* module */[];

var WebContents = /* module */[];

var Critical = Caml_exceptions.create("Electron.Dock.Bounce.Critical");

var Informational = Caml_exceptions.create("Electron.Dock.Bounce.Informational");

var Bounce = /* module */[
  /* Critical */Critical,
  /* Informational */Informational
];

var Dock = /* module */[/* Bounce */Bounce];

var AccessibilitySupportChanged = Caml_exceptions.create("Electron.Electron.App.AccessibilitySupportChanged");

var Activate = Caml_exceptions.create("Electron.Electron.App.Activate");

var BeforeQuit = Caml_exceptions.create("Electron.Electron.App.BeforeQuit");

var BrowserWindowBlur = Caml_exceptions.create("Electron.Electron.App.BrowserWindowBlur");

var BrowserWindowCreated = Caml_exceptions.create("Electron.Electron.App.BrowserWindowCreated");

var BrowserWindowFocus = Caml_exceptions.create("Electron.Electron.App.BrowserWindowFocus");

var ContinueActivity = Caml_exceptions.create("Electron.Electron.App.ContinueActivity");

var GpuProcessCrashed = Caml_exceptions.create("Electron.Electron.App.GpuProcessCrashed");

var Login = Caml_exceptions.create("Electron.Electron.App.Login");

var OpenFile = Caml_exceptions.create("Electron.Electron.App.OpenFile");

var OpenURL = Caml_exceptions.create("Electron.Electron.App.OpenURL");

var Ready = Caml_exceptions.create("Electron.Electron.App.Ready");

var SelectClientCertificate = Caml_exceptions.create("Electron.Electron.App.SelectClientCertificate");

var Quit = Caml_exceptions.create("Electron.Electron.App.Quit");

var WebContentsCreated = Caml_exceptions.create("Electron.Electron.App.WebContentsCreated");

var WillFinishLaunching = Caml_exceptions.create("Electron.Electron.App.WillFinishLaunching");

var WillQuit = Caml_exceptions.create("Electron.Electron.App.WillQuit");

var WindowAllClosed = Caml_exceptions.create("Electron.Electron.App.WindowAllClosed");

var AppData = Caml_exceptions.create("Electron.Electron.App.PathName.AppData");

var Desktop = Caml_exceptions.create("Electron.Electron.App.PathName.Desktop");

var Documents = Caml_exceptions.create("Electron.Electron.App.PathName.Documents");

var Downloads = Caml_exceptions.create("Electron.Electron.App.PathName.Downloads");

var Exe = Caml_exceptions.create("Electron.Electron.App.PathName.Exe");

var Home = Caml_exceptions.create("Electron.Electron.App.PathName.Home");

var Module = Caml_exceptions.create("Electron.Electron.App.PathName.Module");

var Music = Caml_exceptions.create("Electron.Electron.App.PathName.Music");

var PepperFlashSystemPlugin = Caml_exceptions.create("Electron.Electron.App.PathName.PepperFlashSystemPlugin");

var Pictures = Caml_exceptions.create("Electron.Electron.App.PathName.Pictures");

var Temp = Caml_exceptions.create("Electron.Electron.App.PathName.Temp");

var UserData = Caml_exceptions.create("Electron.Electron.App.PathName.UserData");

var Videos = Caml_exceptions.create("Electron.Electron.App.PathName.Videos");

var PathName = /* module */[
  /* AppData */AppData,
  /* Desktop */Desktop,
  /* Documents */Documents,
  /* Downloads */Downloads,
  /* Exe */Exe,
  /* Home */Home,
  /* Module */Module,
  /* Music */Music,
  /* PepperFlashSystemPlugin */PepperFlashSystemPlugin,
  /* Pictures */Pictures,
  /* Temp */Temp,
  /* UserData */UserData,
  /* Videos */Videos
];

var App = /* module */[
  /* AccessibilitySupportChanged */AccessibilitySupportChanged,
  /* Activate */Activate,
  /* BeforeQuit */BeforeQuit,
  /* BrowserWindowBlur */BrowserWindowBlur,
  /* BrowserWindowCreated */BrowserWindowCreated,
  /* BrowserWindowFocus */BrowserWindowFocus,
  /* ContinueActivity */ContinueActivity,
  /* GpuProcessCrashed */GpuProcessCrashed,
  /* Login */Login,
  /* OpenFile */OpenFile,
  /* OpenURL */OpenURL,
  /* Ready */Ready,
  /* SelectClientCertificate */SelectClientCertificate,
  /* Quit */Quit,
  /* WebContentsCreated */WebContentsCreated,
  /* WillFinishLaunching */WillFinishLaunching,
  /* WillQuit */WillQuit,
  /* WindowAllClosed */WindowAllClosed,
  /* PathName */PathName
];

var NativeImage$1 = /* module */[];

var BrowserWindow$1 = /* module */[];

var Electron = /* module */[
  /* App */App,
  /* NativeImage */NativeImage$1,
  /* BrowserWindow */BrowserWindow$1
];

exports.EventEmitter             = EventEmitter;
exports.BrowserWindow            = BrowserWindow;
exports.Certificate              = Certificate;
exports.CommandLine              = CommandLine;
exports.Event                    = Event$1;
exports.ImportCertificateOptions = ImportCertificateOptions;
exports.LoginAuthInfo            = LoginAuthInfo;
exports.LoginItemSettings        = LoginItemSettings;
exports.LoginRequest             = LoginRequest;
exports.Menu                     = Menu;
exports.NativeImage              = NativeImage;
exports.Task                     = Task;
exports.WebContents              = WebContents;
exports.Dock                     = Dock;
exports.Electron                 = Electron;
/* No side effect */
