// Generated by BUCKLESCRIPT VERSION 1.7.1, PLEASE EDIT WITH CARE
'use strict';

var Url        = require("url");
var Path       = require("path");
var Electron   = require("./electron.js");
var Electron$1 = require("electron");

function createWindow() {
  var win = Electron$1.BrowserWindow(800, 600);
  var url = Url.format({
        pathname: Path.join("/var/", "index.html"),
        protocol: "file:",
        slashes: true
      });
  win.loadURL(url);
  win.getWebContents().openDevTools();
  win.on(Electron.BrowserWindow[/* Closed */0], function () {
        return /* () */0;
      });
  return /* () */0;
}

Electron$1.app.on(Electron.Electron[/* App */0][/* Ready */11], createWindow);

exports.createWindow = createWindow;
/*  Not a pure module */
