// Generated by BUCKLESCRIPT VERSION 1.6.0, PLEASE EDIT WITH CARE
'use strict';

var Electron = require("electron");

function createWindow() {
  var win = Electron.BrowserWindow(800, 600);
  return win.loadURL("ok");
}

exports.createWindow = createWindow;
/* electron Not a pure module */
