// Generated by BUCKLESCRIPT VERSION 1.6.0, PLEASE EDIT WITH CARE
'use strict';

var Path     = require("path");
var Electron = require("electron");

function createWindow() {
  var win = Electron.BrowserWindow(800, 600);
  return win.loadURL(Path.join("/var/", "index.html"));
}

exports.createWindow = createWindow;
/* path Not a pure module */
